# Generated by Django 5.1.7 on 2025-07-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='saree',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='saree',
            name='fabric',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
